# Generated by Django 3.2.16 on 2026-05-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="posts_images/", verbose_name="Фото"
            ),
        ),
    ]
